apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app2
  template:
    metadata:
      labels:
        name: app2
        service: service2
        application: wavefront
    spec:
      containers:
        - name: app2
          image: amitvmw/first-k8s-app:2.0.0
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: staging  
spec:
  selector:
    name: app2
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  namespace: staging  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /service2
        pathType: Prefix
        backend:
          service:
            name: app2
            port:
              number: 8080
